### ISSUE TITLE
[PE-D][Tester D] User Guide jump links not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T17-1/tp#152]
The following jump links are not working:
Under Adding your first task: [Jump to Quick Start Guide], [Jump to Add Task Feature]
Under Marking your first task: [Jump to Quick Start Guide]
Under Clearing Default tasks:[Jump to Quick Start Guide] [Jump to Clear Task Feature]
Under Parameters - Common Mistakes:  Task-Related Questions
Command Summary - Clear: (more info)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: kwangthiag/ped#1

**Comment by seantehds** [comment]
Resolved
