### ISSUE TITLE
[PE-D][Tester B] Clear command output window wrong description

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T17-1/tp#154]
![Screenshot 2023-11-03 at 4.24.14 PM.png](https://raw.githubusercontent.com/amosting/ped/main/files/deb69f1a-488d-4185-bf81-4a756f4a21d6.png)

States address book has been cleared but probably y'all meant to refer to taskwise instead.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: amosting/ped#1

**Comment by maypfv** [comment]
The error message now shows "TaskWise ... " instead of "Address book ... "
