### ISSUE TITLE
[PE-D][Tester E] Adding task that is past the deadline

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T17-1/tp#156]
I am not sure if taskWise limits the type of tasks added. Hence, I am not sure if we want our users to add tasks that have a deadline which is past the current date. Perhaps, the Status could be something different ("Overdue"). Or maybe, the user guide can mention this case too, just a suggestion which could perhaps be a feature flaw. 

![Screenshot 2023-11-03 at 4.28.22 PM.png](https://raw.githubusercontent.com/victorlaiyeeteng/ped/main/files/7ff8da6e-1054-4250-9239-e44c5579135a.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: victorlaiyeeteng/ped#2

**Comment by asdfghjkxd** [comment]
Current offerings on the market do not restrict the creation of tasks with deadlines that are before today, but I do agree that alerting users of overdue deadlines would be a great feature to have, and would greatly enhance user experience.

However, as this is a feature flaw/oversight, we will only address it in a future iteration after v1.4.

**Comment by Sebtey** [comment]
Will address this in our future implementations in the documentations
