### ISSUE TITLE
[PE-D][Tester C] Image not showing in user guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T17-1/tp#157]
![image.png](https://raw.githubusercontent.com/javinchua/ped/main/files/c22a456f-775f-47e6-8c83-8de1bfcd6904.png)
The image is not showing.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: javinchua/ped#4

**Comment by JCSnap** [comment]
Related to issue #158
