### ISSUE TITLE
[PE-D][Tester E] Sort command error for 'tsk dsc' prefix description

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T17-1/tp#172]
For the 'sort' command, the UG stated that I can sort the tasks by their task name with the prefix description as 'tsk dsc' and 'task description'. However, taskWise seems to return me an error when I try to use that command.

![Screenshot 2023-11-03 at 4.59.24 PM.png](https://raw.githubusercontent.com/victorlaiyeeteng/ped/main/files/fdb722ba-47e1-4e3b-b2a7-685033146293.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: victorlaiyeeteng/ped#6

**Comment by asdfghjkxd** [comment]
This is not a functionality bug as the JAR file that was used during testing is the older version, whereby this feature was not properly fixed.

The new version of the app allows the aforementioned parameters to be used.

| Before | After |
|:---:|:---:|
| <img width="1009" alt="Screenshot 2023-11-04 at 2 11 42 PM" src="https://github.com/AY2324S1-CS2103T-T17-1/tp/assets/73705042/ec13a75d-9447-46ad-9596-416a5e8b3777"> |  <img width="1009" alt="Screenshot 2023-11-04 at 2 12 24 PM" src="https://github.com/AY2324S1-CS2103T-T17-1/tp/assets/73705042/a45dd46a-4156-48c9-a66c-35720dec15a0"> |

**Comment by asdfghjkxd** [comment]
Closing this issue as this issue is remedied in the new `v1.3.1` release, which was not used in the mock PE.
